# Generated by Django 4.2.11 on 2026-08-07 10:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('server', 'Server / VM / Instance'), ('storage', 'Storage System'), ('network', 'Network Device'), ('backup', 'Backup System / Policy'), ('software', 'Software License'), ('cloud_service', 'Cloud Service / PaaS / SaaS'), ('container', 'Container / K8s Workload'), ('endpoint', 'Endpoint / Workstation'), ('iot', 'IoT / Edge Device'), ('telecom', 'Telecom / UC Equipment'), ('facility', 'Facility / Power / Cooling'), ('other', 'Other')], max_length=30)),
                ('deployment_model', models.CharField(choices=[('on_prem', 'On-Premises'), ('private_cloud', 'Private Cloud'), ('public_cloud', 'Public Cloud'), ('hybrid', 'Hybrid Cloud'), ('multi_cloud', 'Multi-Cloud'), ('edge', 'Edge / Remote Site'), ('colocation', 'Co-location'), ('managed_service', 'Managed Service')], default='on_prem', max_length=30)),
                ('environment', models.CharField(choices=[('prod', 'Production'), ('staging', 'Staging / UAT'), ('dev', 'Development'), ('dr', 'Disaster Recovery'), ('lab', 'Lab / Test'), ('sandbox', 'Sandbox'), ('shared', 'Shared Services')], default='prod', max_length=20)),
                ('data_tier', models.CharField(default='1', max_length=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('retired', 'Retired'), ('expiring', 'Expiring Soon'), ('planned', 'Planned / In Procurement'), ('disposed', 'Disposed'), ('decommissioning', 'Being Decommissioned')], default='active', max_length=30)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('site_name', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('rack_position', models.CharField(blank=True, max_length=100)),
                ('cloud_provider', models.CharField(blank=True, max_length=100)),
                ('cloud_region', models.CharField(blank=True, max_length=100)),
                ('cloud_account_id', models.CharField(blank=True, max_length=255)),
                ('resource_group', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorageSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_type', models.CharField(blank=True, max_length=50)),
                ('solution_name', models.CharField(blank=True, max_length=255)),
                ('raw_capacity_tb', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('usable_capacity_tb', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('media_type', models.CharField(blank=True, max_length=50)),
                ('raid_level', models.CharField(blank=True, max_length=30)),
                ('primary_protocol', models.CharField(blank=True, max_length=30)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_spec', to='assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='ServerSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_role', models.CharField(blank=True, max_length=50)),
                ('server_type', models.CharField(blank=True, max_length=50)),
                ('solution_name', models.CharField(blank=True, max_length=255)),
                ('vcpu_count', models.PositiveIntegerField(blank=True, null=True)),
                ('ram_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('system_disk_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('cloud_instance_type', models.CharField(blank=True, max_length=255)),
                ('os', models.CharField(blank=True, max_length=255)),
                ('cluster_config', models.CharField(blank=True, max_length=50)),
                ('primary_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('availability_zone', models.CharField(blank=True, max_length=100)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='server_spec', to='assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('solution_name', models.CharField(blank=True, max_length=255)),
                ('redundancy_mode', models.CharField(blank=True, max_length=50)),
                ('ports_10g', models.PositiveIntegerField(blank=True, null=True)),
                ('ports_100g', models.PositiveIntegerField(blank=True, null=True)),
                ('management_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=100)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='network_spec', to='assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='CloudSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(blank=True, max_length=50)),
                ('service_name', models.CharField(blank=True, max_length=255)),
                ('service_tier', models.CharField(blank=True, max_length=255)),
                ('billing_model', models.CharField(blank=True, max_length=50)),
                ('monthly_cost_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ha_config', models.CharField(blank=True, max_length=50)),
                ('vcpu_count', models.PositiveIntegerField(blank=True, null=True)),
                ('ram_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('storage_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_spec', to='assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='BackupSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_name', models.CharField(blank=True, max_length=255)),
                ('backup_software', models.CharField(blank=True, max_length=255)),
                ('backup_type', models.CharField(blank=True, max_length=50)),
                ('backup_rule', models.CharField(blank=True, max_length=50)),
                ('daily_retention_days', models.PositiveIntegerField(default=7)),
                ('weekly_retention_weeks', models.PositiveIntegerField(default=4)),
                ('monthly_retention_months', models.PositiveIntegerField(default=12)),
                ('rto_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('rpo_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('encryption', models.CharField(blank=True, max_length=30)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backup_spec', to='assets.asset')),
            ],
        ),
    ]
