# Generated by Django 4.2.11 on 2026-08-08 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_project_alter_user_department_alter_user_division_and_more'),
        ('assets', '0002_asset_created_by_asset_department_asset_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='accounts.project'),
        ),
    ]
