# Generated by Django 4.2.11 on 2026-08-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_organization_alter_asset_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupspec',
            name='controller_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupspec',
            name='disk_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupspec',
            name='disk_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='backupspec',
            name='firmware_storage_os',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='backupspec',
            name='management_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupspec',
            name='raid_level',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='backupspec',
            name='raw_capacity_tb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='backupspec',
            name='usable_capacity_tb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
